"""Command-line interface for awr_analyzer.

Usage:
    awr-analyzer analyze report.html
    awr-analyzer analyze report.html -o insights.html
    awr-analyzer analyze report.html --format text
    awr-analyzer trend day1.html day2.html day3.html -o trend.html
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
from pathlib import Path

from .analyzer import analyze
from .forecast import build_trend
from .parser import AWRParseError, parse_awr_file
from .report import render_html, render_text


def _load_reports(paths):
    reports = []
    for p in paths:
        path = Path(p)
        if not path.exists():
            print(f"error: file not found: {p}", file=sys.stderr)
            sys.exit(2)
        try:
            reports.append(parse_awr_file(str(path)))
        except Exception as exc:  # noqa: BLE001 - surface parser errors clearly to the user
            print(f"error: failed to parse '{p}': {exc}", file=sys.stderr)
            sys.exit(2)
    return reports


def _write_or_print(content: str, out_path, default_name: str):
    if out_path:
        Path(out_path).write_text(content, encoding="utf-8")
        print(f"Wrote {out_path}")
    else:
        print(content)


def cmd_analyze(args) -> None:
    report = _load_reports([args.report])[0]

    if not report.load_profile and not report.top_wait_events and not report.instance_efficiency:
        print(
            "warning: very little recognizable AWR content was found in this file — "
            "double-check it is an Oracle AWR HTML report (generated by awrrpt.sql), "
            "the output below may be incomplete.",
            file=sys.stderr,
        )

    result = analyze(report)

    if args.format == "json":
        payload = dataclasses.asdict(result)
        content = json.dumps(payload, indent=2, default=str)
    elif args.format == "text":
        content = render_text(result)
    else:
        content = render_html(result)

    out_path = args.output
    if out_path is None and args.format == "html":
        out_path = str(Path(args.report).with_suffix("")) + "_analysis.html"
    _write_or_print(content, out_path, "analysis.html")

    _print_console_summary(result)


def cmd_trend(args) -> None:
    reports = _load_reports(args.reports)
    if len(reports) < 2:
        print("error: 'trend' needs at least 2 AWR reports to compare", file=sys.stderr)
        sys.exit(2)

    # Analyze the most recent report normally, and layer the trend on top.
    result = analyze(reports[-1])
    trend = build_trend(reports)

    if args.format == "json":
        payload = {"analysis": dataclasses.asdict(result), "trend": dataclasses.asdict(trend)}
        content = json.dumps(payload, indent=2, default=str)
    elif args.format == "text":
        content = render_text(result, trend=trend)
    else:
        content = render_html(result, trend=trend)

    out_path = args.output
    if out_path is None and args.format == "html":
        out_path = "awr_trend_report.html"
    _write_or_print(content, out_path, "awr_trend_report.html")

    _print_console_summary(result, trend)


def _print_console_summary(result, trend=None) -> None:
    counts = result.counts()
    print(
        f"\nHealth score: {result.health_score}/100  "
        f"(critical={counts.get('critical', 0)}, warning={counts.get('warning', 0)}, "
        f"info={counts.get('info', 0)})"
    )
    if trend:
        risks = trend.emerging_risks()
        if risks:
            print(f"Trend: {len(risks)} metric(s) trending toward a critical threshold.")
        else:
            print("Trend: no metrics are projected to cross a critical threshold at the current rate.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="awr-analyzer",
        description="Analyze Oracle AWR reports and produce plain-language, actionable performance insights.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_analyze = sub.add_parser("analyze", help="Analyze a single AWR HTML report")
    p_analyze.add_argument("report", help="Path to an AWR HTML report")
    p_analyze.add_argument("-o", "--output", help="Output file path (default: <report>_analysis.html)")
    p_analyze.add_argument("--format", choices=["html", "text", "json"], default="html")
    p_analyze.set_defaults(func=cmd_analyze)

    p_trend = sub.add_parser(
        "trend",
        help="Analyze a chronological series of AWR reports and forecast emerging issues",
    )
    p_trend.add_argument(
        "reports", nargs="+",
        help="Paths to 2+ AWR HTML reports, in chronological order (oldest first)",
    )
    p_trend.add_argument("-o", "--output", help="Output file path (default: awr_trend_report.html)")
    p_trend.add_argument("--format", choices=["html", "text", "json"], default="html")
    p_trend.set_defaults(func=cmd_trend)

    return parser


def main(argv=None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except AWRParseError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
