"""Parses an Oracle AWR (Automatic Workload Repository) HTML report into the
structured :class:`~awr_analyzer.models.AWRReport` object used by the rest of
the tool.

AWR HTML reports are generated by ``awrrpt.sql`` / ``awrrpti.sql`` and their
exact markup varies a bit across Oracle versions (10g through 19c/21c), so
this parser avoids relying on fixed anchor names or CSS classes. Instead it:

1. Finds every ``<table>`` in the document.
2. Figures out which "section" a table belongs to by looking at the nearest
   preceding text in the document (the section heading Oracle prints just
   above each table), matched with heuristics/regexes.
3. Parses the table's rows using the table's own header row to figure out
   which column is which, so it degrades gracefully when Oracle renames or
   reorders columns between versions.

Sections that aren't recognized are simply skipped (and recorded in
``raw_section_titles`` for troubleshooting) rather than raising an error, so
a partially-recognized report still produces useful output.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from bs4 import BeautifulSoup, NavigableString, Tag

from .models import AWRReport, SnapshotInfo, SQLStat, TablespaceIOStat, WaitEvent

_SQL_ID_RE = re.compile(r"^[A-Za-z0-9/+]{13}$")


def _to_float(text: Optional[str]):
    """Best-effort conversion of an AWR table cell into a float."""
    if text is None:
        return None
    text = text.strip().replace("\xa0", " ").strip()
    if text in ("", "-", "N/A", "n/a"):
        return None
    negative = text.startswith("(") and text.endswith(")")
    text = text.strip("()")
    text = text.replace(",", "").replace("%", "").strip()
    try:
        value = float(text)
    except ValueError:
        return None
    return -value if negative else value


def _norm(text: Optional[str]) -> str:
    if not text:
        return ""
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _key(text: str) -> str:
    text = _norm(text).lower()
    text = re.sub(r"[():%]", "", text)
    text = re.sub(r"[\s/.-]+", "_", text).strip("_")
    return text


def _row_cells(row: Tag):
    return [_norm(c.get_text(" ")) for c in row.find_all(["td", "th"])]


def _nearby_heading_text(table: Tag, max_chars: int = 400) -> str:
    """Collects the text that appears just before ``table`` in document
    order, stopping once we've walked back past the previous table (so we
    don't pick up an earlier section's trailing content)."""
    parts = []
    total_len = 0
    for el in table.previous_elements:
        if isinstance(el, Tag) and el.name == "table":
            break
        if isinstance(el, NavigableString):
            text = str(el).strip()
            if text:
                parts.append(text)
                total_len += len(text)
        if total_len >= max_chars:
            break
    parts.reverse()
    return _norm(" ".join(parts))


# Ordered so the more specific patterns are tried before generic ones.
_SECTION_PATTERNS = [
    ("sql_elapsed", re.compile(r"sql ordered by elapsed time", re.I)),
    ("sql_cpu", re.compile(r"sql ordered by cpu time", re.I)),
    ("sql_gets", re.compile(r"sql ordered by gets", re.I)),
    ("sql_reads", re.compile(r"sql ordered by reads", re.I)),
    ("sql_executions", re.compile(r"sql ordered by executions", re.I)),
    ("tablespace_io", re.compile(r"tablespace io stats", re.I)),
    ("undo", re.compile(r"undo segment", re.I)),
    ("wait_class", re.compile(r"wait classes? by total wait time", re.I)),
    ("top_wait_events", re.compile(
        r"top \d+ timed (foreground )?events|foreground wait events|top timed events", re.I)),
    ("time_model", re.compile(r"time model statistics", re.I)),
    ("host_cpu", re.compile(r"^host cpu", re.I)),
    ("instance_cpu", re.compile(r"^instance cpu", re.I)),
    ("instance_efficiency", re.compile(r"instance efficiency", re.I)),
    ("load_profile", re.compile(r"load profile", re.I)),
]


def _classify_table(table: Tag) -> Optional[str]:
    heading = _nearby_heading_text(table)
    best_key = None
    best_pos = -1
    for key, pattern in _SECTION_PATTERNS:
        m = None
        for m in pattern.finditer(heading):
            pass
        if m and m.end() > best_pos:
            best_pos = m.end()
            best_key = key
    return best_key


def _header_index(headers: list, *patterns: str) -> Optional[int]:
    for i, h in enumerate(headers):
        for p in patterns:
            if re.search(p, h, re.I):
                return i
    return None


class AWRParseError(Exception):
    pass


def parse_awr_html(html: str, source_path: Optional[str] = None) -> AWRReport:
    soup = BeautifulSoup(html, "lxml")
    report = AWRReport(source_path=source_path)

    _parse_header_info(soup, report)

    for table in soup.find_all("table"):
        section = _classify_table(table)
        rows = table.find_all("tr")
        if not rows:
            continue
        heading = _nearby_heading_text(table)
        if heading:
            report.raw_section_titles.append(heading[:120])

        if section == "load_profile":
            _parse_load_profile(table, report)
        elif section == "instance_efficiency":
            _parse_instance_efficiency(table, report)
        elif section == "top_wait_events":
            _parse_wait_events(table, report.top_wait_events)
        elif section == "wait_class":
            _parse_wait_events(table, report.wait_class_stats, class_col_is_name=True)
        elif section == "time_model":
            _parse_time_model(table, report)
        elif section == "host_cpu":
            _parse_kv_table(table, report.host_cpu)
        elif section == "instance_cpu":
            _parse_kv_table(table, report.instance_cpu)
        elif section in ("sql_elapsed", "sql_cpu", "sql_gets", "sql_reads", "sql_executions"):
            target = {
                "sql_elapsed": report.sql_by_elapsed,
                "sql_cpu": report.sql_by_cpu,
                "sql_gets": report.sql_by_gets,
                "sql_reads": report.sql_by_reads,
                "sql_executions": report.sql_by_executions,
            }[section]
            _parse_sql_table(table, target)
        elif section == "tablespace_io":
            _parse_tablespace_io(table, report.tablespace_io)
        elif section == "undo":
            _parse_kv_table(table, report.undo_stats)

    return report


def parse_awr_file(path: str) -> AWRReport:
    p = Path(path)
    html = p.read_text(encoding="utf-8", errors="replace")
    return parse_awr_html(html, source_path=str(p))


# --------------------------------------------------------------------------
# Section-specific parsers
# --------------------------------------------------------------------------

def _parse_header_info(soup: BeautifulSoup, report: AWRReport) -> None:
    info = report.info
    full_text = soup.get_text("\n")

    def find(pattern):
        m = re.search(pattern, full_text, re.I)
        return _norm(m.group(1)) if m else None

    info.elapsed_minutes = _to_float(find(r"Elapsed:\s*([\d,.\s]+)\(?\s*mins"))
    info.db_time_minutes = _to_float(find(r"DB Time:\s*([\d,.\s]+)\(?\s*mins"))

    for table in soup.find_all("table"):
        headers = [ _key(c) for c in _row_cells(table.find("tr")) ] if table.find("tr") else []
        joined = " ".join(headers)
        if {"db_name", "db_id", "instance"} <= set(headers) or ("db_name" in joined and "instance" in joined):
            data_row = table.find_all("tr")[1] if len(table.find_all("tr")) > 1 else None
            if data_row:
                cells = _row_cells(data_row)
                mapping = dict(zip(headers, cells))
                info.db_name = mapping.get("db_name") or info.db_name
                info.db_id = mapping.get("db_id") or info.db_id
                info.instance_name = mapping.get("instance") or info.instance_name
                info.instance_number = mapping.get("inst_num") or info.instance_number
                info.release = mapping.get("release") or info.release
                info.rac = mapping.get("rac") or info.rac
        if "host_name" in headers and "platform" in headers:
            data_row = table.find_all("tr")[1] if len(table.find_all("tr")) > 1 else None
            if data_row:
                cells = _row_cells(data_row)
                mapping = dict(zip(headers, cells))
                info.host_name = mapping.get("host_name") or info.host_name
                info.platform = mapping.get("platform") or info.platform
                info.cpus = _to_float(mapping.get("cpus")) or info.cpus
                info.cores = _to_float(mapping.get("cores")) or info.cores
                info.sockets = _to_float(mapping.get("sockets")) or info.sockets
                mem_key = next((k for k in mapping if k.startswith("memory")), None)
                if mem_key:
                    info.memory_gb = _to_float(mapping.get(mem_key)) or info.memory_gb

    for row in soup.find_all("tr"):
        cells = _row_cells(row)
        if not cells:
            continue
        label = cells[0].lower()
        if label.startswith("begin snap"):
            if len(cells) > 1:
                info.begin_snap_id = cells[1]
            if len(cells) > 2:
                info.begin_snap_time = cells[2]
        elif label.startswith("end snap"):
            if len(cells) > 1:
                info.end_snap_id = cells[1]
            if len(cells) > 2:
                info.end_snap_time = cells[2]


def _parse_load_profile(table: Tag, report: AWRReport) -> None:
    rows = table.find_all("tr")
    if not rows:
        return
    header_cells = [_key(c) for c in _row_cells(rows[0])]
    # First header cell is usually empty (label column).
    col_names = header_cells[1:] if header_cells else []
    if not col_names:
        col_names = ["per_second", "per_transaction", "per_exec", "per_call"]

    for row in rows[1:]:
        cells = _row_cells(row)
        if len(cells) < 2:
            continue
        label = _key(cells[0])
        if not label:
            continue
        values = {}
        for i, col in enumerate(col_names, start=1):
            if i < len(cells):
                values[col or f"col{i}"] = _to_float(cells[i])
        report.load_profile[label] = values


def _parse_instance_efficiency(table: Tag, report: AWRReport) -> None:
    for row in table.find_all("tr"):
        cells = _row_cells(row)
        # Cells come in (label, value) pairs, possibly two pairs per row.
        for i in range(0, len(cells) - 1, 2):
            label = cells[i]
            value = cells[i + 1]
            if not label or ":" not in label and "%" not in label:
                continue
            key = _key(label)
            val = _to_float(value)
            if key and val is not None:
                report.instance_efficiency[key] = val


def _parse_wait_events(table: Tag, target: list, class_col_is_name: bool = False) -> None:
    rows = table.find_all("tr")
    if not rows:
        return
    headers = [_norm(c) for c in _row_cells(rows[0])]
    if not headers:
        return
    idx_event = _header_index(headers, r"^event$", r"^wait class$" if class_col_is_name else r"^event$")
    idx_waits = _header_index(headers, r"^waits$")
    idx_time = _header_index(headers, r"total wait time", r"^time\s*\(s\)$", r"^time\(s\)$")
    idx_avg = _header_index(headers, r"avg wait", r"wait avg")
    idx_pct = _header_index(headers, r"% *db *time", r"% *total call time", r"%total")
    idx_class = _header_index(headers, r"wait class")

    if idx_event is None:
        idx_event = 0

    for row in rows[1:]:
        cells = _row_cells(row)
        if not cells or idx_event >= len(cells):
            continue
        name = cells[idx_event]
        if not name or name.lower().startswith("total") or set(name) <= {"-"}:
            continue
        we = WaitEvent(
            event=name,
            waits=_to_float(cells[idx_waits]) if idx_waits is not None and idx_waits < len(cells) else None,
            total_wait_time_sec=_to_float(cells[idx_time]) if idx_time is not None and idx_time < len(cells) else None,
            avg_wait_ms=_to_float(cells[idx_avg]) if idx_avg is not None and idx_avg < len(cells) else None,
            pct_db_time=_to_float(cells[idx_pct]) if idx_pct is not None and idx_pct < len(cells) else None,
            wait_class=cells[idx_class] if idx_class is not None and idx_class < len(cells) else None,
        )
        target.append(we)


def _parse_time_model(table: Tag, report: AWRReport) -> None:
    rows = table.find_all("tr")
    if not rows:
        return
    headers = [_norm(c) for c in _row_cells(rows[0])]
    idx_name = _header_index(headers, r"stat name", r"statistic") or 0
    idx_time = _header_index(headers, r"time \(s\)|time\(s\)")
    idx_pct = _header_index(headers, r"% of db time|%.*db.*time")

    for row in rows[1:]:
        cells = _row_cells(row)
        if not cells or idx_name >= len(cells):
            continue
        name = cells[idx_name]
        if not name:
            continue
        report.time_model[_key(name)] = {
            "time_s": _to_float(cells[idx_time]) if idx_time is not None and idx_time < len(cells) else None,
            "pct_db_time": _to_float(cells[idx_pct]) if idx_pct is not None and idx_pct < len(cells) else None,
        }


def _parse_kv_table(table: Tag, target: dict) -> None:
    rows = table.find_all("tr")
    if not rows:
        return
    headers = [_key(c) for c in _row_cells(rows[0])]
    if len(rows) < 2:
        return
    data = _row_cells(rows[1])
    for h, v in zip(headers, data):
        if h:
            target[h] = _to_float(v) if _to_float(v) is not None else v


def _parse_sql_table(table: Tag, target: list) -> None:
    rows = table.find_all("tr")
    if not rows:
        return
    headers = [_norm(c) for c in _row_cells(rows[0])]
    if not headers:
        return

    idx_value = _header_index(
        headers,
        r"elapsed time \(s\)", r"cpu time \(s\)", r"^gets$", r"buffer gets", r"^reads$",
        r"physical reads", r"^executions$",
    )
    idx_exec = _header_index(headers, r"^executions$")
    idx_per_exec = _header_index(headers, r"per exec")
    idx_pct = _header_index(headers, r"%total", r"% *total", r"%cpu", r"% *db *time")
    idx_sqlid = _header_index(headers, r"sql ?id")
    idx_module = _header_index(headers, r"module")
    idx_text = _header_index(headers, r"sql text|text")

    for row in rows[1:]:
        cells = _row_cells(row)
        if not cells:
            continue
        sql_id = None
        if idx_sqlid is not None and idx_sqlid < len(cells):
            sql_id = cells[idx_sqlid]
        if not sql_id:
            sql_id = next((c for c in cells if _SQL_ID_RE.match(c)), None)
        if not sql_id:
            continue
        stat = SQLStat(
            sql_id=sql_id,
            value=_to_float(cells[idx_value]) if idx_value is not None and idx_value < len(cells) else None,
            executions=_to_float(cells[idx_exec]) if idx_exec is not None and idx_exec < len(cells) else None,
            per_exec=_to_float(cells[idx_per_exec]) if idx_per_exec is not None and idx_per_exec < len(cells) else None,
            pct_total=_to_float(cells[idx_pct]) if idx_pct is not None and idx_pct < len(cells) else None,
            module=cells[idx_module] if idx_module is not None and idx_module < len(cells) else None,
            sql_text=cells[idx_text] if idx_text is not None and idx_text < len(cells) else None,
        )
        target.append(stat)


def _parse_tablespace_io(table: Tag, target: list) -> None:
    rows = table.find_all("tr")
    if not rows:
        return
    headers = [_norm(c) for c in _row_cells(rows[0])]
    idx_ts = _header_index(headers, r"tablespace") or 0
    idx_reads = _header_index(headers, r"^reads$")
    idx_avg_reads = _header_index(headers, r"av reads/s|reads/s")
    idx_avg_rd_ms = _header_index(headers, r"av rd\(ms\)|rd\(ms\)")
    idx_writes = _header_index(headers, r"^writes$")
    idx_avg_writes = _header_index(headers, r"av writes/s|writes/s")
    idx_buf_wait = _header_index(headers, r"buf wt\(ms\)|buffer wait")

    for row in rows[1:]:
        cells = _row_cells(row)
        if not cells or idx_ts >= len(cells):
            continue
        name = cells[idx_ts]
        if not name:
            continue
        target.append(TablespaceIOStat(
            tablespace=name,
            reads=_to_float(cells[idx_reads]) if idx_reads is not None and idx_reads < len(cells) else None,
            avg_reads_per_sec=_to_float(cells[idx_avg_reads]) if idx_avg_reads is not None and idx_avg_reads < len(cells) else None,
            avg_read_time_ms=_to_float(cells[idx_avg_rd_ms]) if idx_avg_rd_ms is not None and idx_avg_rd_ms < len(cells) else None,
            writes=_to_float(cells[idx_writes]) if idx_writes is not None and idx_writes < len(cells) else None,
            avg_writes_per_sec=_to_float(cells[idx_avg_writes]) if idx_avg_writes is not None and idx_avg_writes < len(cells) else None,
            avg_buffer_wait_ms=_to_float(cells[idx_buf_wait]) if idx_buf_wait is not None and idx_buf_wait < len(cells) else None,
        ))
